"""empty message

Revision ID: 0c795bcfda22
Revises: eba405578514
Create Date: 2022-07-04 16:14:34.563720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c795bcfda22'
down_revision = 'eba405578514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housedownpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('down_payment_pct', sa.Float(), nullable=True),
    sa.Column('annual_rate', sa.Float(), nullable=True),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('deposit_freq', sa.String(), nullable=True),
    sa.Column('compound_freq', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marriage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('annual_rate', sa.Float(), nullable=True),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('deposit_freq', sa.String(), nullable=True),
    sa.Column('compound_freq', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('annual_rate', sa.Float(), nullable=True),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('deposit_freq', sa.String(), nullable=True),
    sa.Column('compound_freq', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealthcreation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment', sa.Float(), nullable=True),
    sa.Column('annual_rate', sa.Float(), nullable=True),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('deposit_freq', sa.String(), nullable=True),
    sa.Column('compound_freq', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wealthcreation')
    op.drop_table('vacation')
    op.drop_table('marriage')
    op.drop_table('housedownpayment')
    # ### end Alembic commands ###
