"""eigth migration

Revision ID: 121aecd0410a
Revises: 0e3bc2047bd4
Create Date: 2022-07-05 18:09:23.772959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121aecd0410a'
down_revision = '0e3bc2047bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('question1', sa.Integer(), nullable=True),
    sa.Column('question2', sa.Integer(), nullable=True),
    sa.Column('question3', sa.Integer(), nullable=True),
    sa.Column('question4', sa.Integer(), nullable=True),
    sa.Column('question5', sa.Integer(), nullable=True),
    sa.Column('question6', sa.Integer(), nullable=True),
    sa.Column('question7', sa.Integer(), nullable=True),
    sa.Column('question8', sa.Integer(), nullable=True),
    sa.Column('question9', sa.Integer(), nullable=True),
    sa.Column('question10', sa.Integer(), nullable=True),
    sa.Column('question11', sa.Integer(), nullable=True),
    sa.Column('question12', sa.Integer(), nullable=True),
    sa.Column('question13', sa.Integer(), nullable=True),
    sa.Column('question14', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
