"""fifth migrate

Revision ID: c736922a15fc
Revises: 0c795bcfda22
Create Date: 2022-07-04 22:59:44.577489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c736922a15fc'
down_revision = '0c795bcfda22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('a', sa.Text(), nullable=True),
    sa.Column('b', sa.Text(), nullable=True),
    sa.Column('c', sa.Text(), nullable=True),
    sa.Column('d', sa.Text(), nullable=True),
    sa.Column('e', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionsmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionid', sa.Integer(), nullable=True),
    sa.Column('a', sa.Integer(), nullable=True),
    sa.Column('b', sa.Integer(), nullable=True),
    sa.Column('c', sa.Integer(), nullable=True),
    sa.Column('d', sa.Integer(), nullable=True),
    sa.Column('e', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionid'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionsmarks')
    op.drop_table('questions')
    # ### end Alembic commands ###
