"""adding risk profile

Revision ID: eee03413b9d8
Revises: 121aecd0410a
Create Date: 2022-07-05 22:53:56.221934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee03413b9d8'
down_revision = '121aecd0410a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riskprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('type_of_investor', sa.String(length=20), nullable=True),
    sa.Column('accumulation_return', sa.Float(), nullable=True),
    sa.Column('retirement_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riskprofile')
    # ### end Alembic commands ###
